# NEEDED
BINANCE_SECRET_KEY = ""
BINANCE_API_KEY = ""

CMC_KEY = ""

GMAIL_SENDER = ''
GMAIL_SENDER_PW = ''
MAIL_RECIEVER = ''

# NOT NEEDED
REDDIT_ID = ""
REDDIT_SECRET = ""
REDDIT_AGENT = ""  # user agent name
REDDIT_UNAME = ""  # your reddit username
REDDIT_PW = ""

TWITTER_API_KEY = ""
TWITTER_SECRET = ""
TWITTER_BEARER_TOKEN = ""
TWITTER_ACCESS_KEY = ''
TWITTER_ACCESS_TOKEN_SECRET = ''
